### ISSUE TITLE
ReId是用来矫正跟踪框的吗

### ISSUE THREAD

**Issue by mahxn0** [maoyunyao/MOTS_SiamMask#1]
我在结合人脸识别+yolov3+siammask+reid做相关跟踪识别.
大概思路是:在距离摄像头2m左右识别出人脸,取人脸对应的人的框来提取ReId特征,同时这个框当做siammask的初始跟踪框. 后续用reid来矫正跟踪. ReId在Market1501上达到96.5   但是单纯依靠这个来矫正跟踪还是会出现错误..  能否加微信交流一下   18392418428

**Comment by maoyunyao** [comment]
你好,目前我们ReID模块的初步想法为减少遮挡情况下的IDSwitch, 实现间隔数帧同一目标的关联

**Comment by maoyunyao** [comment]
> 我在结合人脸识别+yolov3+siammask+reid做相关跟踪识别.
> 大概思路是:在距离摄像头2m左右识别出人脸,取人脸对应的人的框来提取ReId特征,同时这个框当做siammask的初始跟踪框. 后续用reid来矫正跟踪. ReId在Market1501上达到96.5 但是单纯依靠这个来矫正跟踪还是会出现错误.. 能否加微信交流一下 18392418428

**Comment by maoyunyao** [comment]
你好,目前我们ReID模块的初步想法为减少遮挡情况下的IDSwitch, 实现间隔数帧同一目标的关联
